name: Integration Tests and Coverage

on:
  pull_request:
    branches:
      - development
      - "release-**"
      - main
  push:
        branches:
          - development
          - "release-**"
          - main 
jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
 
    steps:
 
    - uses: actions/checkout@v4
 
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC
 
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
 
    - name: Install Python dependencies
      run: |
        sudo apt install -y $(grep -o ^[^#][[:alnum:]-]* "packages.list")
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
     
    - name: Checkout
      uses: actions/checkout@v4     
    - name: Execute tests
      working-directory: ./
      run: make integration-tests
      